var fs = require('fs');

/*
 * @constructor
 */
function MsOfficeWordHTMLWriter(options) {
    var options = options || {};

    this.head         = options.head       || "";
    this.hf_head      = options.hf_head    || "";
    this.title        = options.title      || "Document generated by MsOfficeWordHTMLWriter";
    this.sections     = options.sections   || [];
    this.MIME_parts   = options.MIME_parts || [];
    this.WordDocument = options.WordDocument;
}

MsOfficeWordHTMLWriter.prototype = {
    create_section: function() {

    },

    write: function() {

    },

    save_as: function() {

    },

    field: function() {

    },

    attach: function(callback) {

    },

    page_break: function(pbreak) {
        return "<br clear='all' style='page-break-before:" + (pbreak || 'always') + "'>\n";
    },

    tab: function(n_tabs) {
        return "<span style='mso-tab-count:" + (n_tabs || 1) + "'></span>";
    }
};

exports.MsOfficeWordHTMLWriter = MsOfficeWordHTMLWriter;